#!/bin/bash

# macOS Create Photo Year Structure Script
# Creates organized photo folders for a specific year
# Part of the Life Atlas digital organization system
# Version: 1.0.0
# Repository: https://github.com/andrewhml/life-atlas

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PHOTOS_DIR="$SCRIPT_DIR"

# Set default year to current year
CURRENT_YEAR=$(date +%Y)

echo "Life Atlas - Create Photo Year Structure"
echo "======================================="
echo ""

# Get year from user or use command line argument
if [ $# -eq 1 ]; then
    # Year provided as command line argument
    YEAR="$1"
    echo "Using year from command line: $YEAR"
else
    # Get year from user input
    read -p "Enter year (default: $CURRENT_YEAR): " input
    YEAR="${input:-$CURRENT_YEAR}"
    echo "Using year: $YEAR"
fi

echo ""

# Validate year format (4 digits)
if ! [[ "$YEAR" =~ ^[0-9]+$ ]] || [ ${#YEAR} -ne 4 ]; then
    echo "❌ Error: Year must be exactly 4 digits (e.g., 2025)"
    echo "   You entered: '$YEAR'"
    exit 1
fi

# Check if year is reasonable (between 1900 and 2100)
if [ "$YEAR" -lt 1900 ] || [ "$YEAR" -gt 2100 ]; then
    echo "❌ Error: Year must be between 1900 and 2100"
    echo "   You entered: $YEAR"
    exit 1
fi

YEAR_FOLDER="$PHOTOS_DIR/${YEAR}-Photos"

# Check if year folder already exists
if [ -d "$YEAR_FOLDER" ]; then
    echo "⚠️  Folder ${YEAR}-Photos already exists!"
    read -p "Continue and add missing subfolders? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Operation cancelled."
        exit 0
    fi
    echo ""
fi

echo "📁 Creating photo structure for year $YEAR..."
echo ""

# Create year folder structure
mkdir -p "$YEAR_FOLDER"/{RAW,Processed,Video}

# Create monthly RAW folders with zero-padded months
echo "📅 Creating monthly folders..."
for month in 01 02 03 04 05 06 07 08 09 10 11 12; do
    MONTH_FOLDER="$YEAR_FOLDER/RAW/${YEAR}-${month}"
    mkdir -p "$MONTH_FOLDER"
    
    # Create example organization folders in first month only
    if [ "$month" == "01" ]; then
        mkdir -p "$MONTH_FOLDER/Memories"
        mkdir -p "$MONTH_FOLDER/Locations"
        
        # Create README for organization options
        cat > "$MONTH_FOLDER/README.md" << EOL
# ${YEAR}-${month} Photos

Raw photo files for $(date -j -f "%Y-%m" "${YEAR}-${month}" "+%B %Y" 2>/dev/null || echo "Month $month, $YEAR").

## Organization Options

You can organize photos in this folder by:

### By Memories/Events
Use the Memories/ subfolder or create folders like:
- Vacation-Trip/
- Birthday-Party/
- Weekend-Hiking/

### By Locations
Use the Locations/ subfolder or create folders like:
- Boston-Area/
- New-York-Trip/
- Home/

### Or keep flat
Just place all RAW files directly in this month folder.

## Workflow
1. Import RAW files here from camera/drone
2. Process in Lightroom (catalog in ../../../Lightroom-Library/)
3. Export processed JPGs to ../${YEAR}-Photos/Processed/

Generated by Life Atlas on $(date)
EOL
    fi
done

# Create main year folder README
cat > "$YEAR_FOLDER/README.md" << EOL
# ${YEAR} Photos

Photo organization for the year ${YEAR}.

## Folder Structure

### RAW/
Monthly folders (${YEAR}-01 through ${YEAR}-12) containing:
- Raw camera files organized by month
- Optional Memories/ and Locations/ subfolders for organization

### Processed/
Final exported JPG images from Lightroom/editing

### Video/
Video files captured during ${YEAR}

## Recommended Workflow

1. **Import**: Camera/drone content → RAW/YYYY-MM/
2. **Process**: Edit in Lightroom (catalog in ../Lightroom-Library/)
3. **Export**: Processed JPGs → Processed/
4. **Archive**: Move to long-term storage when year complete

## Organization Tips

- Use consistent naming for events (e.g., "2025-03-15_Birthday-Party")
- Keep Lightroom catalog in parent directory for consistency
- Archive completed years to NAS or external storage
- Consider creating yearly backup before major edits

Generated by Life Atlas on $(date)
EOL

echo "✅ Photo structure created successfully!"
echo ""
echo "📂 Created folders:"
echo "   📁 ${YEAR}-Photos/"
echo "      📁 RAW/ (with monthly subfolders ${YEAR}-01 through ${YEAR}-12)"
echo "         📁 ${YEAR}-01/ (with example Memories/ and Locations/ folders)"
echo "      📁 Processed/"
echo "      📁 Video/"
echo "      📄 README.md"
echo ""
echo "📋 Next steps:"
echo "1. Import photos to appropriate monthly RAW folders"
echo "2. Use Lightroom catalog in ../Lightroom-Library/"
echo "3. Export processed images to ${YEAR}-Photos/Processed/"
echo "4. Organize by Memories or Locations as needed"
echo ""
echo "🗺️  Part of the Life Atlas digital organization system"
echo "    Repository: https://github.com/andrewhml/life-atlas"