#!/usr/bin/env bash
# install-hooks.sh — wire the personal-data lint into the repo's pre-commit hook.
#
# Idempotent — safe to re-run. Always overwrites .git/hooks/pre-commit with
# the canonical shim (since the shim's content is deterministic, re-running
# produces the same file).
#
# Run once after cloning life-atlas on a new device:
#   bash scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "ERROR: not inside a git working tree" >&2
  exit 1
}

LINT="$REPO_ROOT/scripts/lint-no-personal-data.sh"
HOOK="$REPO_ROOT/.git/hooks/pre-commit"
DENYLIST="${LINT_DENYLIST:-$HOME/Atlas/config/atlas/lint-denylist.txt}"

if [[ ! -f "$LINT" ]]; then
  echo "ERROR: lint script not found at $LINT" >&2
  exit 1
fi

[[ -x "$LINT" ]] || chmod +x "$LINT"

mkdir -p "$REPO_ROOT/.git/hooks"

# Write a shim (not a symlink) so the hook explicitly documents which mode
# it runs in and survives any worktree-level git config quirks.
cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh.
# Runs the personal-data lint over staged content before commit.
exec "$(git rev-parse --show-toplevel)/scripts/lint-no-personal-data.sh" --staged
EOF
chmod +x "$HOOK"

echo "Installed pre-commit hook at: $HOOK"
echo "  → runs: $LINT --staged"
echo ""

# Warn (not fail) if the deny-list isn't present yet — the lint will error
# clearly on first commit, but a heads-up here is friendlier.
if [[ ! -f "$DENYLIST" ]]; then
  echo "WARNING: deny-list not found at $DENYLIST" >&2
  echo "  The hook will fail on first commit until you create it. Seed from:" >&2
  echo "    mkdir -p \"\$(dirname \"$DENYLIST\")\"" >&2
  echo "    cp \"$REPO_ROOT/scripts/lint-denylist.example.txt\" \"$DENYLIST\"" >&2
  echo "  Then replace EXAMPLE_* placeholders with your real tokens." >&2
  exit 0
fi

echo "Deny-list found at: $DENYLIST"
